### ISSUE TITLE
[Hunting] To do

### ISSUE THREAD

**Issue by aikaterna** [aikaterna/aikaterna-cogs#102]
~~cancel hunting task on unload~~ f05dad4
~~add server based leaderboard~~ 56f4f20a82b556366a2418a63932a33e36899842
~~#16~~ 6c08f175cda18b742fe4bbcb2e7003c4f5172dee

**Comment by Brandjuh** [comment]
Since there is a to-do for hunting, I will post my feature request here :-) 

I would like to see a economy integration with hunting. I have thinking about it, maybe selling the animals or even process them to make them more worth to gain some money. To make you lose some money, you need to buy a gun to shoot and ammunition. 
Or maybe even go deeper with it and make guns decay and you need to buy a new one, etc etc.

**Comment by aikaterna** [comment]
This is a somewhat internal todo list for myself. I have moved your request to a new issue as I will be closing this issue when I'm done with it.
