### ISSUE TITLE
[Feature Request] command to see what's playing on radio

### ISSUE THREAD

**Issue by Kovaelin** [aikaterna/aikaterna-cogs#20]
I've seen some music bots that are able to give the name of the artist and the song. Most online radio stations also have this information on their page. Would it be possible to introduce a feature like this into the cog too? Thanks.

**Comment by aikaterna** [comment]
Hey there, while I can definitely appreciate your request, and it's been on my todo list for radio for a while, I don't see myself adding this soon. I had done work in the past with icyparser and getting it to display titles like this (and you can see the usage in my radio repository), but I had to modify the package for Windows to get it to work. I spend most of my time for coding audio on Red v3's audio cog nowadays which can mostly do what you're asking (it doesn't have auto-update for stream titles unfortunately, and it was on my list to see about trying to get that done at some point - or see it supported in the java dependency we use for v3 audio through someone else's work. I can understand your earlier comments about liking the radio cog because it was had very low memory usage compared to v3 audio, but there's even alternative jars built for v3's audio nowadays that can do things like run on Android systems and other low power devices. There's also flags to limit the amount of memory used by the jar on the device as well. If you have any interest in any of this please feel free to DM or friend me in Discord.

**Comment by Kovaelin** [comment]
I appreciate the follow-up. Thank you.
