### ISSUE TITLE
[Rndstatus] Custom status instead of Playing/Streaming/Listening/...

### ISSUE THREAD

**Issue by cchrkk** [aikaterna/aikaterna-cogs#232]
Hello and thanks for your cogs.
I have one question, why is there no Custom Status type for rndstatus? Is this feature limited to actual users and not to bots?

Am I looking at the wrong documentation [here ](https://discord.com/developers/docs/topics/gateway#activity-object-activity-types)?

Ty and sorry if it's something obvious

**Comment by aikaterna** [comment]
It's not currently possible.

https://discord.com/developers/docs/topics/gateway#activity-object
"Bots are only able to send name, type, and optionally url."

As bots cannot send states or emojis, they can't make effective use of custom statuses. The header for a "Custom Status" shows up on their profile, but there is no actual custom status, because those fields are ignored.

See also: https://github.com/discord/discord-api-docs/issues/1160

**Comment by cchrkk** [comment]
Wow what a bummer, almost 2 years old issue and it doesn't look like it
will get fixed anytime soon.
It would be useful because "is playing" "is listening to", ecc wastes a lot
of space.

Thanks anyway 🤷 <https://emojipedia.org/person-shrugging/>

Il giorno lun 17 mag 2021 alle ore 16:41 aikaterna ***@***.***>
ha scritto:
