### ISSUE TITLE
[Away] Request to toggle embed format

### ISSUE THREAD

**Issue by Kovaelin** [aikaterna/aikaterna-cogs#52]
I use an IRC bridge, and this cog seems like it would be very useful for people on the IRC side to see who is online/away. However, embeds don't work with the bridge. Would it be possible to have an option to toggle the embedded messages as regular messages please? Thank you.

**Comment by aikaterna** [comment]
Hi Kovaelin, I mentioned the other day I would take a look at this and add some logic to respect the bot's embed toggle. However when I opened it up to look at it I see that if the bot doesn't have embed_message permissions in the channel it's replying in... it will send a text-based message instead of an embed. You can remove the bot's embed message perms and this will function as you requested. Let me know if this works for you.

**Comment by Kovaelin** [comment]
If I do that, then it affects everything, including when the bot provides links to images and some features in other cogs. Would it be possible to include a toggle that only affects Away itself? There's a bit of a mixture of cogs that use embeds and cogs that don't in my bridge channel. Thanks again.
